### ISSUE TITLE
Fatal error: Can't use method return value in write context

### ISSUE THREAD

**Issue by oneotacoop** [yulioaj290/smart-shopify-product#1]
I Installed Smart Shopify plugin and it says    
Fatal error: Can't use method return value in write context in /home4/oneota/public_html/wp-content/plugins/smart-shopify-product/smart-shopify-product.php on line 160

Line 160 states
 if (empty($my_query->have_posts())) {

Any Help would be great! Thanks

**Comment by yulioaj290** [comment]
@oneotacoop Review your PHP version, if it is 5.5 or lower, then you must to upgrade PHP to 5.6 or higher.

Look the official [documentation for the `empty()` function](http://php.net/empty) and note that:

> Note: Prior to PHP 5.5, empty() only supports variables; anything else will result in a parse error. In other words, the following will not work: empty(trim($name)). Instead, use trim($name) == false.
